name: Build Resume

on:
  push:
    branches:
      - main

jobs:
  build_resume:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: docker://pandoc/latex:3.5

      - name: Install WeasyPrint
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
          pip install weasyprint

      - name: Build Resumes
        run: |
          chmod +x ./build.sh
          ./build.sh

      - uses: actions/upload-artifact@v4
        with:
          name: resume-outputs
          path: out/ 