name: Build Resume
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Pandoc
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc
      
      - name: Install WeasyPrint dependencies
        run: |
          sudo apt-get install -y python3-pip python3-cffi python3-brotli libpango-1.0-0 libharfbuzz0b libpangoft2-1.0-0
          pip install weasyprint
      
      - name: Build Resume
        run: |
          chmod +x ./build.sh
          ./build.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resume-outputs
          path: |
            out/*.html
            out/*.pdf 
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
