name: Deploy Resume

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc weasyprint

      - name: Create Output Directory
        run: mkdir -p output

      - name: Set Environment Variables
        run: |
          echo "OUTPUT_DIR=output" >> $GITHUB_ENV

      - name: Generate HTML Version
        run: ./build.sh resume html

      - name: Generate PDF Version
        run: ./build.sh resume pdf

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          force_orphan: true